apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway-redis
  labels:
    app.kubernetes.io/name: gateway-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - image: redis:latest
        name: redis
      restartPolicy: Always
