apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway-redis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app.kubernetes.io/name: gateway-redis
    app.kubernetes.io/instance: {{ .Release.Name }}

