apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: gateway-redis
    spec:
      containers:
      - image: redis:latest
        name: gateway-redis
      restartPolicy: Always
