language: java

env:
  global:
    - VERIFY_USE_PUBLIC_BINARIES=true
    - secure: "lQ0rlJwFtLRbk8aAexwXLKZUp6LNuC9TGhHUsYD92WGTT03QDTGDbpbpQXStLEPthMzbrX1qPp+GmcTqRKHgSISP6LAXOeAuI6AZtuc0NKzLd/425JiaksytDv0m4rfuozRveUyZRMq/geqTRvtEuRiW6qDKRT8l0emtkT2olM584gTp2fJZw9k6TgTPebrj70N9Ec7T3DSYBqaFnNduHHRBVlbqmrnGF6tfMGQZ0rcOZFiMYpIuwaX9b5+rfTR5ZjbuWzyjK0MQdfH8stFGSiAYcwu3+Wfp7w416SnwQh/J2plFcA8I2pKZ9Gl63eQBGeGAyh+4fqYZz7XiqFkoaBCKOyHDHtPeqdbNZCU0fgzbfdCBjULUiI51ItF1SFDg21WxxS3gJBkh1wBMU14CvYpcQOwe5rKc1emdfuRndmTrpheOehXjdF3eYfQlqAnIeyzMlpYf3PzNWJojjSLy0be/Q97pA6S44+RVWVJEz57BiEV+Hxy9rp9S/JFR2TSCCHEF7g9flGeX6ImTcz274eKtRAIU2Tx9MqbBcDkY/CfevrO1usaV6qQ4uheZxhjxzj5WkZ/p21+r2GZNHffgQylYlIqiG4ZJHlFBU4fpdD+Tb6y/sPyjMJdgIxMU1q4YSu5nux21LQ3bmKp7WvcJx+NzfQmQ2E4QSW21LvYrOpA="
    - secure: "E/Ui52SP8jC9kvP9RxYcvrP2Q3BPyKdi/almVWEfWetBKDH7g9M1bl6pgTLTrI31CZGS0O2MtOC05vTp7KkksveBwhbvXLOcb934bLpeOP0son3gXDH5ANTwOq98amFlyKbqzZre0BUMeIPtHc1ZoGc5s6q5a+nZ78zgyjiDVc9StlRx38QcF0rM7S9zzcIqu0eNoLTI4pDI/cP0STpIG68rsGKQSVUI5dFAGC0ZdVIEH7rSP/G5rPbX4scvwiQ2iBaPuaOkPvgfAW7Th4reQK3/97C+ShfC3aNfPfCYZoSYBROHSrgFqvSsEOGjiKnuqaz07RcGsh1tAXLrzcYVey3YExxiPVIYEY8q5P5nCjE0pT65AJqnnXT0gJ/+zLV9I5x4DPEBRcgURDAhVgMRTlOobE0VLb2rvsTdUZpiopVoAQUQEH1s8rD1LA1EqethRI3IHBv9jK63ca0gwwQcKh6KxZE8YxjsiVTXPjRu64XFz0OlH4PBn7ZNja/b0aGeaQt/qoxGHTQ3/xkuiVArg1WfVKo1ZW9jOG5R2vOiV6Lbxkmcb+pkMUF9X8JvzUYNUjNFqHA2119lXbamVKG2gAzi6dlmFldpyyU8rdJONdrRmdAlAKq10Cre2QEPFzh1ehHIMrRVlxT0pi7BQM7aH2sKZzFeifhpL5+0J698emo="

jdk:
  - openjdk11

before_install:
  - sudo apt-get install jq
  - curl -u ida-codacy-bot:$GITHUB_PAT -LSs $(curl -u ida-codacy-bot:$GITHUB_PAT -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({content_type, browser_download_url} | select(.content_type | contains("java-archive"))) | .[0].browser_download_url') -o codacy-coverage-reporter-assembly.jar

install:
  - npm install -g snyk@1.146.0

script:
  - ./gradlew --no-daemon --quiet test
  - snyk/test.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

after_success:
  - snyk/monitor.sh
  - ./gradlew jacocoTestReport
  - java -jar codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml


cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
