version: '3'

services:
  docker-gradle:
    build:
      context: .
      dockerfile: softHSM.baseImage.Dockerfile
      args:
        baseImage: gradle:jdk11
    working_dir: /home/gradle/project
    user: root
    entrypoint: gradle --no-daemon
    environment:
      VERIFY_USE_PUBLIC_BINARIES: 'true'
    volumes:
      - gradle-cache:/home/gradle/.gradle
      - .:/home/gradle/project
    image: govukverify/soft-hsm
        
volumes:
  gradle-cache:
