apiVersion: v1
kind: Service
metadata:
  annotations:
  name: {{ .Release.Name }}-stub-connector
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 31100
  - name: "6667"
    port: 6667
    targetPort: 6667
  selector:
    app.kubernetes.io/name: stub-connector
    app.kubernetes.io/instance: {{ .Release.Name }}
