apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-stub-idp-postgres
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app.kubernetes.io/name: stub-idp-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
