apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-stub-metadata
  labels:
    app.kubernetes.io/name: stub-metadata
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: stub-metadata
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stub-metadata
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: http
        args:
        - ruby
        - -run
        - -ehttpd
        - /srv
        - -p80
        image: ruby:2.4.4
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /srv
          name: saml-metadata
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: saml-metadata
        secret:
          secretName: saml-metadata
