apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-stub-metadata
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: stub-metadata
    app.kubernetes.io/instance: {{ .Release.Name }}
