apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-stub-idp
spec:
  type: NodePort
  ports:
  - name: "6200"
    port: 6200
    targetPort: 80
    nodePort: 31300
  selector:
    app.kubernetes.io/name: stub-idp
    app.kubernetes.io/instance: {{ .Release.Name }}
