apiVersion: verify.gov.uk/v1beta1
kind: Metadata
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: {{ .Release.Name }}-proxy-metadata
spec:
  id: _entities
  type: proxy
  data:
    entityID: https://{{ include "gateway.host" . }}
    postURL: https://{{ include "gateway.host" . }}/SAML2/SSO/POST
    redirectURL: https://{{ include "gateway.host" . }}/Redirect
    orgName: {{ .Release.Name }}
    orgDisplayName: {{ .Release.Name }}
    orgURL: https://www.gov.uk/verify
    contactCompany: GOV.UK Verify
    contactGivenName: GOV.UK Verify
    contactSurname: Support
    contactEmail: idasupport@digital.cabinet-office.gov.uk
  enabled: true
