apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-translator
spec:
  ports:
  - name: "6300"
    port: 6300
    targetPort: 80
  - name: "6661"
    port: 6661
    targetPort: 6661
  selector:
    app.kubernetes.io/name: translator
    app.kubernetes.io/instance: {{ .Release.Name }}
