server:
  applicationConnectors:
    - type: http
      port: ${PORT:-50140}
  adminConnectors:
    - type: http
      port: 50141
  requestLog:
    appenders:
      - type: console

logging:
  level: INFO
  loggers:
    uk.gov.ida: DEBUG
  appenders:
    - type: console
    - type: file
      currentLogFilename: logs/stub-idp.log
      archive: false

assertionLifetime: 60m

saml:
  entityId: http://stub_idp.acme.org/{0}/SSO/POST

hubEntityId: ${HUB_ENTITY_ID}

serviceInfo:
  name: stub-idp

signingKeyPairConfiguration:
  privateKeyConfiguration:
    keyFile: ${IDP_SIGNING_PRIVATE_KEY}
  publicKeyConfiguration:
    certFile: ${IDP_SIGNING_CERT}
    name: idp.signing.cert

basicAuthEnabledForUserResource: true

stubIdpsYmlFileLocation: ${STUB_IDPS_FILE_PATH}
stubIdpYmlFileRefresh: 10s

infinispan:
  type: standalone
  persistenceToFileEnabled: false
  persistenceFileLocation: apps-local-data/infinispanStubIdpCache

assets:
  overrides:
    /assets: build/resources/main/assets

metadata:
  uri: ${METADATA_URL}
  trustStore:
    path: ${METADATA_TRUST_STORE}
    password: ${METADATA_TRUST_STORE_PASSWORD}

stubCountryMetadataUrl: ${STUB_COUNTRY_METADATA_URL:-http://DefaultNotUsed}
connectorNodeUrl: https://${SIGNIN_DOMAIN}/SAML2/SSO/EidasResponse/POST
connectorNodeIssuerId: ${HUB_CONNECTOR_ENTITY_ID:-http://DefaultNotUsed}