apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-parser
spec:
  type: NodePort
  ports:
  - name: "6400"
    port: 6400
    targetPort: 80
    nodePort: 31400
  - name: "6008"
    port: 6008
    targetPort: 6008
  selector:
    app.kubernetes.io/name: parser
    app.kubernetes.io/instance: {{ .Release.Name }}
