apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "metadata-controller.fullname" . }}-customer-ca-crt
  labels:
    app: {{ template "metadata-controller.name" . }}
    chart: {{ template "metadata-controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  customerCA.crt: {{ required "A valid .Values.customerCaCrt entry required!" .Values.customerCaCrt | b64enc | quote }}
