apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "metadata-controller.fullname" . }}
  labels:
    app: {{ include "metadata-controller.name" . }}
    chart: {{ include "metadata-controller.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
