apiVersion: v1
kind: Service
metadata:
  name: proxy-node-translator
spec:
  ports:
  - name: "6300"
    port: 6300
    targetPort: 80
  - name: "6661"
    port: 6661
    targetPort: 6661
  selector:
    service: proxy-node-translator
