apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy-node-gateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: proxy-node-gateway
    spec:
      containers:
      - env:
        - name: CONNECTOR_NODE_ENTITY_ID
          valueFrom:
            configMapKeyRef:
              name: proxy-node-pki
              key: CONNECTOR_NODE_ENTITY_ID
        - name: CONNECTOR_NODE_ISSUER_ID
          valueFrom:
            configMapKeyRef:
              name: proxy-node-pki
              key: CONNECTOR_NODE_ISSUER_ID
        - name: CONNECTOR_NODE_METADATA_TRUSTSTORE
          valueFrom:
            configMapKeyRef:
              name: proxy-node-pki
              key: CONNECTOR_NODE_METADATA_TRUSTSTORE
        - name: CONNECTOR_NODE_METADATA_TRUSTSTORE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: proxy-node-pki
              key: CONNECTOR_NODE_METADATA_TRUSTSTORE_PASSWORD
        - name: CONNECTOR_NODE_METADATA_URL
          value: http://stub-connector.default.svc.cluster.local/Metadata
        - name: CONNECTOR_NODE_URL
          valueFrom:
            configMapKeyRef:
              name: proxy-node-pki
              key: CONNECTOR_NODE_URL
        - name: HUB_ENTITY_ID
          value: https://dev-hub.local
        - name: HUB_FACING_ENCRYPTION_CERT
          valueFrom:
            configMapKeyRef:
              name: proxy-node-pki
              key: HUB_FACING_ENCRYPTION_CERT
        - name: HUB_FACING_ENCRYPTION_KEY
          valueFrom:
            configMapKeyRef:
              name: proxy-node-pki
              key: HUB_FACING_ENCRYPTION_KEY
        - name: HUB_FACING_SIGNING_CERT
          valueFrom:
            configMapKeyRef:
              name: proxy-node-pki
              key: HUB_FACING_SIGNING_CERT
        - name: HUB_FACING_SIGNING_KEY
          valueFrom:
            configMapKeyRef:
              name: proxy-node-pki
              key: HUB_FACING_SIGNING_KEY
        - name: HUB_METADATA_TRUSTSTORE
          valueFrom:
            configMapKeyRef:
              name: proxy-node-pki
              key: HUB_METADATA_TRUSTSTORE
        - name: HUB_METADATA_TRUSTSTORE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: proxy-node-pki
              key: HUB_METADATA_TRUSTSTORE_PASSWORD
        - name: HUB_METADATA_URL
          value: http://proxy-node-metadata.default.svc.cluster.local/metadata_for_hub.xml
        - name: HUB_URL
          valueFrom:
            configMapKeyRef:
              name: proxy-node-pki
              key: HUB_URL
        - name: METADATA_REFRESH_DELAY
          value: "60000"
        - name: PORT
          value: "80"
        - name: PROXY_NODE_AUTHN_REQUEST_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: proxy-node-pki
              key: PROXY_NODE_AUTHN_REQUEST_ENDPOINT
        - name: PROXY_NODE_ENTITY_ID
          value: https://dev-hub.local
        - name: PROXY_NODE_METADATA_FOR_CONNECTOR_NODE_URL
          value: http://proxy-node-metadata.default.svc.cluster.local/metadata_for_connector_node.xml
        - name: PROXY_NODE_RESPONSE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: proxy-node-pki
              key: PROXY_NODE_RESPONSE_ENDPOINT
        - name: REDIS_SERVER_URI
          value: redis://gateway-redis.default.svc.cluster.local:6379/
        - name: SIGNING_CERT
          valueFrom:
            configMapKeyRef:
              name: proxy-node-pki
              key: SIGNING_CERT
        - name: SIGNING_KEY
          valueFrom:
            configMapKeyRef:
              name: proxy-node-pki
              key: SIGNING_KEY
        - name: TRANSLATOR_URL
          value: http://proxy-node-translator.default.svc.cluster.local:6300/SAML2/SSO/Response/POST
        image: govukverify/proxy-node-gateway
        name: proxy-node-gateway
        ports:
        - containerPort: 80
        - containerPort: 6601
      restartPolicy: Always
