apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hsm
  labels:
    app.kubernetes.io/name: hsm
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: pkcs11
    port: 5656
    targetPort: 5656
  selector:
    app.kubernetes.io/name: hsm
    app.kubernetes.io/instance: {{ .Release.Name }}
